apiVersion: postgresql.org/v1
kind: PostgresDatabase
metadata:
  name: app3
spec:
  dbName: db3
  dbRoleName: user3
  dbRolePassword: swordfish
  dbExtensions:
    - hstore
  extraSQL: |
    CREATE TABLE example (
      user_id serial PRIMARY KEY,
      username VARCHAR (50) UNIQUE NOT NULL,
      email VARCHAR (355) UNIQUE NOT NULL
    );
    INSERT INTO example (user_id, username, email) VALUES (1, 'user1', 'user1@email.com');
